### PR TITLE
Add phpCE elePHPant

### PR DESCRIPTION
**Pull request by cookieguru**

### CODE REVIEW

**Comment by cookieguru** [comment]
Ping @dseguy

**Comment by cookieguru** [comment]
@akiojalehto Looks like this is another one not manufactured by Custom Plush Toys.  Submitted #97 to remove it.

https://phpug.slack.com/archives/C195M60A2/p1540753148007100

**Comment by philipsharp** [comment]
I'm not in the PHP UG Slack. Can you tell me what the message is from there?

**Comment by cookieguru** [comment]
Screenshot of #elephpants on phpug Slack

**Comment by dseguy** [comment]
I am finding some extra information on this question.  :)

**Pull request merged**
