### PR TITLE
Add blue shopware elephpant

### PR DESCRIPTION
**Pull request by bcremer**
Fix issue https://github.com/philipsharp/afieldguidetoelephpants/issues/25.

### CODE REVIEW

**Comment by ins0** [comment]
That was quick thanks @bcremer - Ok now i need to fix some Shopware Bugs :>

**Comment by philipsharp** [comment]
What is the license for this photo and who took it?

**Comment by ins0** [comment]
ping @bcremer

**Comment by bcremer** [comment]
This photo was taken by my co-worker @Weltraumakustik. 

@Weltraumakustik is it OK for you to licence the photo under the [Creative Commons
Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/)?

**Comment by Weltraumakustik** [comment]
Yes. My photo is licensed under [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/) – feel free to use it :+1:

**Pull request merged**
