### PR TITLE
added Enfys the Rainbow elephpant

### PR DESCRIPTION
**Pull request by snoek09**
https://www.kickstarter.com/projects/1817732114/the-phpdiversity-rainbow-elephpant

Based on https://github.com/MarkBaker/afieldguidetoelephpants/commit/a813bb0b14ddd4222e29d2ba1dd67357c5c8d0c6

### CODE REVIEW

**Comment by philipsharp** [comment]
I like to wait until the campaign is finished before adding any Kickstarted elephpants. I'm going to leave this open until then.

**Comment by cookieguru** [comment]
@philipsharp But if we add it now it may help raise awareness of the campaign, which still has a ways to go to meet its goal.

**Comment by snoek09** [comment]
@philipsharp this project was successfully funded 42 days ago.

**Comment by MarijnKoesen** [comment]
👍  For the Diversity Elephpant

**Pull request merged**
