### PR TITLE
Add the new PHP Roundtable elePHPant

### PR DESCRIPTION
**Pull request by SammyK**
The new PHP Roundtable elePHPant was [unveiled today](https://www.phproundtable.com/episode/secret-project-revealed)!

### CODE REVIEW

**Comment by OGProgrammer** [comment]
+1

**Comment by philipsharp** [comment]
Since this is a new sub-species, it will need a new name. The names are set in app/config/sculpin_site.yml, keyed by the category (`phproundtable`).

I try to come up with a suggestion but I'm a little stumped for this one.

**Comment by ShaunaGordon** [comment]
`circumensi`? `circumensai`? `circumensae`?

Literal Latin translation of "roundtable" is "circum mensam" (at least according to Google Translate, I'm by no means a Latin scholar). I'm also not familiar with the rules for Latin names for fauna, so I'm spitballing a little.

**Comment by SammyK** [comment]
Oops! Thanks @philipsharp, I totally missed that file. I've updated it with @ShaunaGordon's lovely suggestion, `circumensi`! :D

**Comment by philipsharp** [comment]
Good suggestion. (Fake Latin is accepted here!)

**Pull request merged**
