### PR TITLE
Add a new elephpant, purple from PHPCon Poland

### PR DESCRIPTION
**Pull request by akiojalehto**
Fulfills issue #57

### CODE REVIEW

**Comment by MarkBaker** [comment]
Is the Purple PHPCon elephpant a real, official elephpant?

**Comment by cookieguru** [comment]
@MarkBaker See #57

**Comment by akiojalehto** [comment]
I think we should close this and only add official elephpants to the field guide.

**Comment by philipsharp** [comment]
Agreed.

**Pull request closed without merging**
