### PR TITLE
Add photos for blue zend

### PR DESCRIPTION
**Pull request by ojalehto**
Add photos requested in issue #2

### CODE REVIEW

**Comment by ins0** [comment]
Thanks @ojalehto could you please update the images - see https://github.com/philipsharp/afieldguidetoelephpants/blob/master/CONTRIBUTING.md

**Comment by ojalehto** [comment]
Hmm, what do you mean? Local images are in the correct path with requested size. If `link` would be absent then local images would be wrapped in an empty links in generated page.

**Comment by ins0** [comment]
You're right. Sry i missread the line :)

Am Samstag, 27. Februar 2016 schrieb Aki Ojalehto :

> Hmm, what do you mean? Local images are in the correct path with requested
> size. If link would be absent then local images would be wrapped in an
> empty links in generated page.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/philipsharp/afieldguidetoelephpants/pull/39#issuecomment-189675867>
> .
>


-- 


_____________________
Marco Rieger
Flachsstraße 16
32369 Rahden
Germany

0171-5540818

https://racecore.de <http://racecore.de/>

**Comment by ins0** [comment]
You're right. Sry i missread the line :)

**Comment by ojalehto** [comment]
Ok :)

**Comment by philipsharp** [comment]
Thanks. I was beginning to think these didn't exist. There are very few pictures of them.

**Pull request merged**
