### PR TITLE
Update 2015-06-02-brown-truenorthphp.md

### PR DESCRIPTION
**Pull request by pmeth**

### CODE REVIEW

**Comment by pmeth** [comment]
Thanks Tim. That's a nice picture. I have added it to the PR.

**Comment by pmeth** [comment]
If you would like to do a proper picture of the right side, it would be better than the prototype (which is missing the TrueNorthPHP logo)

**Comment by cookieguru** [comment]
Here we go:

24931999432_ff26153a3e_m

https://www.flickr.com/photos/atomictaco/24931999432/

And congrats to @SyntaxC4 for picking the name!

**Comment by pmeth** [comment]
awesome thanks

**Comment by philipsharp** [comment]
Thanks for the updates @pmeth and for the great photos @cookieguru .

**Pull request merged**
